custom_teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.25

    axis_angular:  # Left thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 1.4 # 25% of turbo speed

    enable_button: 5  # Right trigger button
    
    # Turbo mode settings (= MAX SPEED)
    enable_turbo_button: 4 # Left trigger button
    scale_linear_turbo:
      x: 1.0
    scale_angular_turbo:
      yaw: 5.6 # 1 / (WHEEL_D/2) such that PWM = 255


    decrease_button: 0 # "A" button to decrease speed
    increase_button: 3 # "Y" button to increase speed

    speed_increment: 0.1




joystick_commands:
  ros__parameters:
    still_button: 1 # "B" button to take a picture
    led_button: 2   # "X" button to toggle the LED
