clc
clear
close all

objFile = 'ground_floor_env.obj';

[V,F] = readObjTri(objFile);

V = V/1000;
V = V - mean(V,1);

figure('Color','w','Name','Environment')

subplot(1,2,1)
patch('Vertices',V,...
      'Faces',F,...
      'FaceColor',[0 0 0],...
      'EdgeColor',[0.35 0.35 0.35],...
      'FaceAlpha',1);

axis equal
grid on
view(35,25)
xlabel('X (m)')
ylabel('Y (m)')
zlabel('Z (m)')
title('Environment - 3D View')

subplot(1,2,2)
patch('Vertices',V,...
      'Faces',F,...
      'FaceColor',[0 0 0],...
      'EdgeColor',[0.35 0.35 0.35],...
      'FaceAlpha',1);

axis equal
grid on
view(2)
xlabel('X (m)')
ylabel('Y (m)')
title('Environment - Top View')
hold on

text(-0.23, 0.25, 'Kitchen / Breakfast', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'Color','r')

text(0.01, 0.31, 'Study', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'Color','r')

text(0.30, 0.22, 'Lounge', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'Color','r')

text(-0.26, -0.01, 'Utility Room', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'Color','r')

text(0.02, -0.01, 'Hall', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'Color','r')

text(0.13, -0.01, 'Store', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'Color','r')

text(-0.20, -0.37, 'Master Bedroom', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'Color','r')

text(0.28, -0.37, 'Bedroom 2', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'Color','r')

sgtitle('Environment','FontWeight','bold')

function [V,F] = readObjTri(filename)

fid = fopen(filename,'r');

if fid == -1
    error('Could not open OBJ file')
end

V = [];
F = [];

while true
    tline = fgetl(fid);

    if ~ischar(tline)
        break
    end

    tline = strtrim(tline);

    if startsWith(tline,'v ')
        vals = sscanf(tline(3:end),'%f');
        if numel(vals) >= 3
            V(end+1,:) = vals(1:3)';
        end
    elseif startsWith(tline,'f ')
        parts = strsplit(tline);
        idx = zeros(1,numel(parts)-1);

        for i = 2:numel(parts)
            token = parts{i};
            tokenParts = strsplit(token,'/');
            idx(i-1) = str2double(tokenParts{1});
        end

        idx = idx(~isnan(idx));
        idx = idx(idx > 0);

        if numel(idx) == 3
            F(end+1,:) = idx;
        elseif numel(idx) > 3
            for k = 2:numel(idx)-1
                F(end+1,:) = [idx(1) idx(k) idx(k+1)];
            end
        end
    end
end

fclose(fid);
F = unique(F,'rows');

end